[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
test = "test"
cache_path = "cache/forge"
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = false

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@safe-global/=lib/safe-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "safe-contracts/=lib/safe-contracts/contracts/",
]

# Enable ffi for advanced testing
ffi = true

# Gas reporting
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
